medicineshop/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Translate with middleware
Route::group(['middleware' => 'localization'], function(){

    Route::get('/', 'Frontend\HomeController@index')->name('welcome');
    Route::get('/search', 'Frontend\HomeController@search')->name('frontend.search');
    Route::get('/search/json', 'Frontend\HomeController@jsonSearch');
    Route::get('change-language', 'Frontend\HomeController@changeLanguage')->name('change-language');

    Route::get('/redirect/{providerName}', 'Frontend\SocialAuthController@redirect')->name('auth.social');
    Route::get('/callback/{providerName}', 'Frontend\SocialAuthController@callback');

    Auth::routes();

    Route::group(['prefix' => 'admin', 'middleware' => 'isAdmin'], function () {
        Route::get('/', 'Admin\AdminController@index');
        Route::match(['get', 'post'], 'setup', 'Admin\AdminController@setup')->name('admin.setup');
        Route::get('json/getStaticstics', 'Admin\AdminController@getStaticstics');

        Route::resource('users', 'Admin\UserController');

        Route::resource('category', 'Admin\CategoryController');
        Route::get('category/{id}/create', 'Admin\CategoryController@subCreate')->name('category.subCreate');

        Route::resource('medicine', 'Admin\MedicineController');

        Route::resource('comment', 'Admin\CommentController');

        Route::resource('rate', 'Admin\RateController');

        Route::resource('request', 'Admin\RequestMedicineController');

        Route::get('orders', 'Admin\OrderController@index')->name('admin.orders.index');
        Route::get('orders/{id}/detail', 'Admin\OrderController@orderDetail')->name('admin.orders.detail');
        Route::put('orders/{id}/detail', 'Admin\OrderController@changeStatus')->name('admin.orders.change');
    });

    Route::group(['middleware' => 'isLogin'], function(){
        // Prescription
        Route::get('/prescription', 'Frontend\PrescriptionController@index')
            ->name('frontend.prescription.index');
        Route::get('/prescription/json/getList', 'Frontend\PrescriptionController@getJsonList');
        Route::delete('/prescription/{id}', 'Frontend\PrescriptionController@destroyPrescription');
        
        Route::get('/prescription/{id}/edit', 'Frontend\PrescriptionController@editPrescription');
        Route::put('/prescription/{id}/edit', 'Frontend\PrescriptionController@updatePrescription')
            ->name('frontend.prescription.update');

        Route::get('/prescription/addnew', 'Frontend\PrescriptionController@addNewPrescription')
            ->name('frontend.prescription.addnew');
        Route::post('/prescription/addnew', 'Frontend\PrescriptionController@storeNewPrescription')
            ->name('frontend.prescription.store');
        Route::get('/prescription/json/searchMedicines', 'Frontend\PrescriptionController@jsonSeachMedicines');

        // Mark Medicine
        Route::get('/mark-medicine', 'Frontend\HomeController@markMedicineIndex')
            ->name('frontend.mark-medicine.index');
        Route::delete('/mark-medicine/{id}', 'Frontend\HomeController@markMedicineDestroy')
            ->name('frontend.mark-medicine.destroy');

        Route::get('detail/add-to-box', 'Frontend\DetailMedicinesController@addToBox')->name('add_to_box');

        // Add comment
        Route::post('/comment/send/data', 'Frontend\DetailMedicinesController@addEditComment');
        Route::post('/comment/send/data/children', 'Frontend\DetailMedicinesController@addEditChildrenComment');
        Route::post('/comment/delete/children', 'Frontend\DetailMedicinesController@deleteChildrenComment');

        Route::post('/user/edit', 'Frontend\UserProfilesController@editUserInformations')
            ->name('frontend.user.edit.personal');
        Route::post('/user/edit/upload', 'Frontend\UserProfilesController@showUploadAvatar')
            ->name('show_upload_avatar');
        Route::post('/user/change-password', 'Frontend\UserProfilesController@userChangePassword')
            ->name('user_change_password');
        Route::get('/user/profile', 'Frontend\UserProfilesController@index')
            ->name('frontend.user.profiles');

            
        Route::get('/request-prescription', 'Frontend\RequestPrescriptionController@requestIndex')
        	->name('request-prescription.index');
        Route::get('/request-prescription/add-new', 'Frontend\RequestPrescriptionController@requestAddnew')
        	->name('request-prescription.addnew');
        Route::post('/request-prescription/add-new', 'Frontend\RequestPrescriptionController@requestStore')
        	->name('request-prescription.store');
        Route::get('/request-prescription/json/detail', 'Frontend\RequestPrescriptionController@jsonDetail');
        Route::get('/request-prescription/json/doctorDetail', 'Frontend\RequestPrescriptionController@jsonDoctorDetail');

        Route::get('/request-medicine', 'Frontend\RequestMedicineController@requestIndex')
            ->name('frontend.request-medicine.index');
        Route::get('/request-medicine/add-new', 'Frontend\RequestMedicineController@requestAddnew')
            ->name('frontend.request-medicine.addnew');
        Route::post('/request-medicine/add-new', 'Frontend\RequestMedicineController@requestStore')
            ->name('frontend.request-medicine.store');
        Route::get('/request-medicine/json/detail', 'Frontend\RequestMedicineController@jsonDetail');

        Route::get('/doctor-request-prescription', 'Frontend\RequestPrescriptionController@doctorRequestIndex')
            ->name('doctor-request-prescription.index');
        Route::get('/doctor/{id}/make-prescrition', 'Frontend\PrescriptionController@doctorMakePrescription')
            ->name('frontend.doctor.make-prescription');
        Route::post('/doctor/{id}/make-prescrition', 'Frontend\PrescriptionController@doctorStorePrescription')
            ->name('frontend.doctor.prescription.store');

        Route::get('/convert-prescription/{id}/order', 'Frontend\OrderController@convertToOrder')
            ->name('frontend.convert.order');
        Route::get('checkout', 'Frontend\OrderController@checkout')->name('frontend.checkout');
        Route::post('checkout', 'Frontend\OrderController@checkoutStore')->name('frontend.checkout.store');
        Route::get('order-view/{id}/detail', 'Frontend\OrderController@detailOrder')
            ->name('frontend.order.detail');
        Route::put('order-view/{id}/detail', 'Frontend\OrderController@changeStatus')
            ->name('frontend.order.change');
        Route::get('checkout/success', 'Frontend\OrderController@orderSuccess')
            ->name('frontend.order.success');
        Route::get('user/order-list', 'Frontend\OrderController@orderList')
            ->name('frontend.order.list');
        Route::post('/order/resend/email', 'Frontend\OrderController@resendEmail');
    });

    Route::get('/user/{user_id}/{user_name}', 'Frontend\UserProfilesController@profileDiffUser')
        ->name('frontend.user.different.profiles');

    Route::get('/doctor/list-all', 'Frontend\HomeController@doctorList')->name('frontend.doctor.list');
    Route::get('/doctor/json/getList', 'Frontend\HomeController@jsonDoctorList');

    Route::post('/detail/{id}/review', 'Frontend\DetailMedicinesController@reviewMedicine');

    Route::get('/contact/sendemail', 'Frontend\HomeController@indexSendEmail')->name('frontend.contact.index');
    Route::post('/contact/sendemail', 'Frontend\HomeController@sendEmail')->name('frontend.sendemail');

    // Comment
    Route::get('/comment/json/getList', 'Frontend\DetailMedicinesController@jsonCommentList');

    // Detail medicine
    Route::get('detail/{id}/{name}', 'Frontend\DetailMedicinesController@index')->name('detail');

    Route::get('/{parent}', 'Frontend\MedicinesListController@showParentCategories')->name('nav');
    Route::get('/{parentLink}/{subLink}', 'Frontend\MedicinesListController@showSubCategory')->name('sub_Nav');
});

medicineshop/resources/views/admin/request/list.blade.php
@extends('admin.layouts.admin-layout')

@section('pageAdminTitle', __('Request Medicine'))

@section('content')
<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        {{ __('Request Medicine') }}
        <small>{{ __('List') }}</small>
    </h1>
    <ol class="breadcrumb">
        <li><a href="{!! url('admin') !!}"><i class="fa fa-dashboard"></i>{{ __('Home') }}</a></li>
        <li class="active">{{ __('Request Medicine') }}</li>
    </ol>
</section>

<!-- Main content -->
<section class="content">
    <div class="row">
        <div class="col-xs-12">
            <div class="box">
                <div class="box-header">
                    <div class="col-md-10">
                        <h3 class="box-title">{{ __('Request Medicine') }}</h3>
                    </div>
                    <div class="col-md-2 text-right">
                        <a href="" data-toggle="tooltip" title="" class="btn btn-default" data-original-title="{{ __('Rebuild') }}"><i class="fa fa-refresh"></i></a>
                    </div>
                </div><!-- /.box-header -->
                <div class="box-body">
                    <table id="user_list_table" class="table table-bordered table-hover">
                        <thead>
                        <tr>
                            <th>{{ __('ID #') }}</th>
                            <th>{{ __('Medicine Name') }}</th>
                            <th>{{ __('Short Describer') }}</th>
                            <th>{{ __('User') }}</th>
                            <th>{{ __('Created At') }}</th>
                            <th>{{ __('Status') }}</th>
                            <th>{{ __('Action') }}</th>
                        </tr>
                        </thead>
                        <tbody>

                        @php
                            $requestMedicines = $data['requestMedicine']
                        @endphp

                        @foreach ($requestMedicines as $requestMedicine)
                            <tr>
                                <td>
                                    <span>{{ $requestMedicine->id }}</span>
                                </td>
                                <td>
                                    <span>{{ $requestMedicine->medicine_name }}</span>
                                </td>
                                <td>
                                    <span>{!! str_limit($requestMedicine->short_describer, 120) !!}</span>
                                </td>
                                <td>
                                    <span>
                                        @if ($requestMedicine->getUser)
                                            {{ $requestMedicine->getUser->display_name }}
                                        @endif
                                    </span>
                                </td>
                                <td>
                                    <span>{{ $requestMedicine->created_at }}</span>
                                </td>
                                <td class="text-center">
                                    @if ($requestMedicine->status === App\Eloquent\RequestMedicine::STATUS_NOT_SEEN)
                                        <div class="btn btn-danger text-center">
                                            <i class="fa fa-eye-slash"></i>
                                            <span>{{ __('Not seen') }}</span>
                                        </div>
                                    @elseif ($requestMedicine->status === App\Eloquent\RequestMedicine::STATUS_WATCHED)
                                        <div class="btn btn-primary text-center">
                                            <i class="fa fa-eye"></i>
                                            <span>{{ __('Watched') }}</span>
                                        </div>
                                    @else
                                        <div class="btn btn-info text-center">
                                            <i class="fa fa-share-square-o"></i>
                                            <span>{{ __('Has responded') }}</span>
                                        </div>
                                    @endif
                                </td>
                                <td class="text-right">
                                    <span class="text-right">
                                        <a href="{{ route('request.edit', [$requestMedicine->id]) }}" data-toggle="tooltip" class="btn btn-primary" data-original-title="{{ __('View Detail') }}">
                                            <i class="fa fa-eye"></i>
                                        </a>
                                    </span>
                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                    {{ $requestMedicines->links() }}
                </div><!-- /.box-body -->
            </div><!-- /.box -->
        </div><!-- /.col -->
    </div><!-- /.row -->
</section><!-- /.content -->
@endsection

medicineshop/resources/views/admin/request/view.blade.php
@extends('admin.layouts.admin-layout')

@php
    $requestMedicine = $data['requestMedicine']
@endphp

@section('pageAdminTitle', __('Detail request medicine :name', ['name' => $requestMedicine->medicine_name]))

@section('content')

<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>{{ __('Detail request medicine :name', ['name' => $requestMedicine->medicine_name]) }}</h1>
    <ol class="breadcrumb">
        <li><a href="{!! url('admin') !!}"><i class="fa fa-dashboard"></i>{{ __('Home') }}</a></li>
        <li class="active">{{ __('Detail request medicine :name', ['name' => $requestMedicine->medicine_name]) }}</li>
    </ol>
</section>

<!-- Main content -->
<section class="content">
    <div class="row">
        <div class="col-xs-12">
            <div class="box">
                <div class="box-header">
                    <div class="col-md-10"></div>
                    <div class="col-md-2 text-right">
                        {!! Form::button(__('Save'), ['type' => 'submit', 'form' => 'save-request-medicine', 'data-toggle' => 'tooltip', 'class' => 'btn btn-primary', 'data-original-title' => __('Save')]) !!}
                        <a href="{!! route('request.index') !!}" data-toggle="tooltip" class="btn btn-default" data-original-title="{{ __('Cancel') }}">
                            <i class="fa fa-reply"></i>
                        </a>
                    </div>
                </div><!-- /.box-header -->
                <div class="box-body">
                    <div class="col-sm-12">
                        <div class="panel panel-info">
                            <!-- Default panel contents -->
                            <div class="panel-heading">
                                <i class="fa fa-medkit"></i>
                                <span>{{ $requestMedicine->medicine_name }}</span>
                            </div>
                            <div class="panel-body">
                                <!-- List group -->
                                <ul class="list-group">
                                    @if ($requestMedicine->getUser)
                                        <li class="list-group-item">
                                            <span class="label label-info">{{ __('User') }}</span>
                                            <span>
                                                {{ 
                                                    $requestMedicine->getUser->display_name
                                                }}
                                            </span>
                                        </li>
                                    @endif
                                    <li class="list-group-item">
                                        <span class="label label-info">{{ __('Short Describer') }}</span>
                                        <span>{{ $requestMedicine->short_describer }}</span>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>

                    {!! Form::open(['route' => ['request.update', $requestMedicine->id], 'id' => 'save-request-medicine', 'class' => 'form-horizontal', 'method' => 'PUT']) !!}

                        <div class="form-group">
                            <div class="col-sm-1"></div>
                            @foreach ($requestMedicine->getAllImages as $image)
                                <div class="col-sm-2">
                                    <img src="{{ url($image->path_origin) }}" class="img-thumbnail max-height-200px" alt="{{ $requestMedicine->medicine_name }}">
                                </div>
                            @endforeach
                        </div>
                        
                        <div class="form-group">
                            <div class="col-sm-12">
                                {!! Form::label('status', __('Status'), ['class' => 'col-sm-1 control-label']) !!}
                                <div class="col-sm-11">
                                    {!! Form::select('status', $data['option'], $requestMedicine->status, ['class' => 'form-control']) !!}
                                    <span class="text-danger">{!! $errors->first('status') !!}</span>
                                </div>
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-sm-12">
                                {!! Form::label('respone_admin', __('Respone By Admin'), ['class' => 'col-sm-1 control-label']) !!}

                                <div class="col-sm-11">
                                    {!! Form::textarea('respone_admin', $requestMedicine->respone_admin, ['class' => 'form-control', 'placeholder' => __('Respone By Admin'), 'rows' => '6']) !!}
                                    <span class="text-danger">{!! $errors->first('respone_admin') !!}</span>
                                </div>
                            </div>
                        </div>
                    {!! Form::close() !!}

                </div><!-- /.box-body -->
            </div><!-- /.box -->
        </div><!-- /.col -->
    </div><!-- /.row -->
</section><!-- /.content -->
@endsection